// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function getDatabaseUrl(): string | undefined {
  if (process.env["SQL_HOST"] && process.env["SQL_ADMIN_USER"]) {
    const user = encodeURIComponent(process.env["SQL_ADMIN_USER"]);
    const pass = encodeURIComponent(process.env["SQL_ADMIN_PASSWORD"] || "");
    const host = encodeURIComponent(process.env["SQL_HOST"]);
    const db = process.env["SQL_DB_NAME"] || "cloud_sql_development_database";
    return `postgresql://${user}:${pass}@localhost/${db}?host=${host}`;
  }
  const dbUrl = process.env["DATABASE_URL"];
  if (dbUrl && !dbUrl.includes("<") && !dbUrl.includes(">")) {
    return dbUrl;
  }
  return undefined;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
    ...(process.env["DIRECT_URL"] ? { directUrl: process.env["DIRECT_URL"] } : {}),
  },
});
